apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: prod
  annotations:
    iam.gke.io/gcp-service-account: gke-worm-sa@internal-507903.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worm-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worm-app
  template:
    metadata:
      labels:
        app: worm-app
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: app-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
      - name: app
        image: nginxinc/nginx-unprivileged:alpine
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: worm-storage
          mountPath: /var/log/app-archive
      volumes:
      - name: worm-storage
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: my-worm-bucket-data-internal-507903
            mountOptions: "implicit-dirs,file-mode=644,dir-mode=755"